<?php

namespace CarBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{
    public function getCarsWithAllDetails()
    {
        $qb = $this->createQueryBuilder('carRepository');

        $qb->select('carRepository','make','model');
        $qb->join('carRepository.make','make');
        $qb->join('carRepository.model', 'model');

        return $qb->getQuery()->getResult();
    }

    public function getCarWithDetails($id)
    {
        $qb = $this->createQueryBuilder('carRepository');

        $qb->select('carRepository','make','model');
        $qb->join('carRepository.make','make');
        $qb->join('carRepository.model', 'model');

        $qb->where('carRepository.id = :id');
        $qb->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }
}
