services:
    car.data_checker:
        class: CarBundle\Service\DataChecker
        arguments: ["%enable_promoting%","@doctrine.orm.entity_manager"]
#        arguments: ["@service_id", "plain_value", "%parameter%"]
